export enum TypeActions {
    ADD_TYPE = 'ADD_TYPE',
    ADD_PRODUCT = 'ADD_PRODUCT',
    ADD_TO_CART = 'ADD_TO_CART',
    SET_STANDART_FILTER = 'SET_STANDART_FILTER',
    SET_PRICE_FILTER = 'SET_PRICE_FILTER',
    SET_TYPE_FILTER = 'SET_TYPE_FILTER'
}